image: fedora:latest

variables:
    CARGO_TARGET_DIR: "target"

stages:
  - build
  - test

default:
  artifacts:
    paths:
      - $CARGO_TARGET_DIR

before_script:
  - dnf install -y gcc gcc-c++ systemd-devel mingw64-gcc
  - dnf clean all
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  - source $HOME/.cargo/env
  - rustup target add x86_64-pc-windows-gnu

build_debug_job_linux:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
  script:
    - rustc --version && cargo --version
    - cargo build

build_debug_job_windows:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
  script:
    - rustc --version && cargo --version
    - cargo build --target x86_64-pc-windows-gnu

build_release_job_linux:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  script:
    - rustc --version && cargo --version
    - cargo build --release

build_release_job_windows:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  script:
    - rustc --version && cargo --version
    - cargo build --release --target x86_64-pc-windows-gnu

test_job:
  stage: test
  script:
    - cargo test --workspace --verbose
