name: CI

on:
  push:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    env:
      CARGO_TARGET_DIR: target

    steps:
      - name: Install dependencies
        run: |
          dnf install -y git gcc gcc-c++ systemd-devel mingw64-gcc

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "##[add-path]$HOME/.cargo/bin"
          source $HOME/.cargo/env
          rustup target add x86_64-pc-windows-gnu

      - name: Checkout repository
        run: |
          cd /workspace/fisuri
          git clone https://altlinux.space/fisuri/claws.git
          cd claws
          
      - name: Build debug for Linux
        if: github.ref == 'refs/heads/dev'
        run: |
          git switch dev
          rustc --version && cargo --version
          cargo build

      - name: Build debug for Windows
        if: github.ref == 'refs/heads/dev'
        run: |
          git switch dev
          rustc --version && cargo --version
          cargo build --target x86_64-pc-windows-gnu

      - name: Build release for Linux
        if: github.ref == 'refs/heads/master'
        run: |
          git switch master
          rustc --version && cargo --version
          cargo build --release

      - name: Build release for Windows
        if: github.ref == 'refs/heads/master'
        run: |
          git switch master
          rustc --version && cargo --version
          cargo build --release --target x86_64-pc-windows-gnu

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: target
      #     path: ${{ env.CARGO_TARGET_DIR }}
