use iced::keyboard::key::Code;

#[derive(Debug, Clone, Default)]
pub struct KeypadButton {
  pub id: usize,
  pub label: String,
  pub vec_str: Vec<String>,
  pub code: Vec<u8>,
}

impl KeypadButton {
  pub fn reduce_label(element: &str) -> String {
    match element {
      "Control" => "Ctrl".to_string(),
      "Delete" => "Del".to_string(),
      "Escape" => "Esc".to_string(),
      "ArrowUp" => "↑".to_string(),
      "ArrowRight" => "→".to_string(),
      "ArrowDown" => "↓".to_string(),
      "ArrowLeft" => "←".to_string(),
      _ => element.to_string(),
    }
  }
}

pub trait CodeAscii {
  fn to_ascii(&self) -> Option<u8>;
}

impl CodeAscii for Code {
  fn to_ascii(&self) -> Option<u8> {
    match self {
      Code::Backquote => Some(b'`'),
      Code::Backslash | Code::IntlBackslash => Some(b'\\'),
      Code::BracketLeft => Some(b'['),
      Code::BracketRight => Some(b']'),
      Code::Comma => Some(b','),
      Code::Digit0 => Some(b'0'),
      Code::Digit1 => Some(b'1'),
      Code::Digit2 => Some(b'2'),
      Code::Digit3 => Some(b'3'),
      Code::Digit4 => Some(b'4'),
      Code::Digit5 => Some(b'5'),
      Code::Digit6 => Some(b'6'),
      Code::Digit7 => Some(b'7'),
      Code::Digit8 => Some(b'8'),
      Code::Digit9 => Some(b'9'),
      Code::Equal => Some(b'='),
      Code::KeyA => Some(b'a'),
      Code::KeyB => Some(b'b'),
      Code::KeyC => Some(b'c'),
      Code::KeyD => Some(b'd'),
      Code::KeyE => Some(b'e'),
      Code::KeyF => Some(b'f'),
      Code::KeyG => Some(b'g'),
      Code::KeyH => Some(b'h'),
      Code::KeyI => Some(b'i'),
      Code::KeyJ => Some(b'j'),
      Code::KeyK => Some(b'k'),
      Code::KeyL => Some(b'l'),
      Code::KeyM => Some(b'm'),
      Code::KeyN => Some(b'n'),
      Code::KeyO => Some(b'o'),
      Code::KeyP => Some(b'p'),
      Code::KeyQ => Some(b'q'),
      Code::KeyR => Some(b'r'),
      Code::KeyS => Some(b's'),
      Code::KeyT => Some(b't'),
      Code::KeyU => Some(b'u'),
      Code::KeyV => Some(b'v'),
      Code::KeyW => Some(b'w'),
      Code::KeyX => Some(b'x'),
      Code::KeyY => Some(b'y'),
      Code::KeyZ => Some(b'z'),
      Code::Minus | Code::NumpadSubtract => Some(b'-'),
      Code::Period => Some(b'.'),
      Code::Quote => Some(b'\''),
      Code::Semicolon => Some(b';'),
      Code::Slash | Code::NumpadDivide => Some(b'/'),
      Code::AltLeft => Some(0x82),
      Code::AltRight => Some(0x86),
      Code::Backspace => Some(0xb2),
      Code::CapsLock => Some(0xc1),
      Code::ControlLeft => Some(0x80),
      Code::ControlRight => Some(0x84),
      Code::Enter => Some(0xb0),
      Code::SuperLeft => Some(0x83),
      Code::SuperRight => Some(0x87),
      Code::ShiftLeft => Some(0x81),
      Code::ShiftRight => Some(0x85),
      Code::Space => Some(b' '),
      Code::Tab => Some(0xb3),
      Code::Delete => Some(0xd4),
      Code::End => Some(0xd5),
      Code::Home => Some(0xd2),
      Code::Insert => Some(0xd1),
      Code::PageDown => Some(0xd6),
      Code::PageUp => Some(0xd3),
      Code::ArrowDown => Some(0xd9),
      Code::ArrowLeft => Some(0xd8),
      Code::ArrowRight => Some(0xd7),
      Code::ArrowUp => Some(0xda),
      Code::NumLock => Some(0xdb),
      Code::Numpad0 => Some(0xea),
      Code::Numpad1 => Some(0xe1),
      Code::Numpad2 => Some(0xe2),
      Code::Numpad3 => Some(0xe3),
      Code::Numpad4 => Some(0xe4),
      Code::Numpad5 => Some(0xe5),
      Code::Numpad6 => Some(0xe6),
      Code::Numpad7 => Some(0xe7),
      Code::Numpad8 => Some(0xe8),
      Code::Numpad9 => Some(0xe9),
      Code::NumpadAdd => Some(0xdf),
      Code::NumpadComma => Some(b','),
      Code::NumpadEnter => Some(0xe0),
      Code::NumpadEqual => Some(b'='),
      Code::NumpadHash => Some(b'#'),
      Code::NumpadMultiply | Code::NumpadStar => Some(b'*'),
      Code::NumpadParenLeft => Some(b'('),
      Code::NumpadParenRight => Some(b')'),
      Code::Escape => Some(0xb1),
      Code::PrintScreen => Some(0xce),
      Code::ScrollLock => Some(0xcf),
      Code::Pause => Some(0xd0),
      Code::F1 => Some(0xc2),
      Code::F2 => Some(0xc3),
      Code::F3 => Some(0xc4),
      Code::F4 => Some(0xc5),
      Code::F5 => Some(0xc6),
      Code::F6 => Some(0xc7),
      Code::F7 => Some(0xc8),
      Code::F8 => Some(0xc9),
      Code::F9 => Some(0xca),
      Code::F10 => Some(0xcb),
      Code::F11 => Some(0xcc),
      Code::F12 => Some(0xcd),
      Code::F13 => Some(0xf0),
      Code::F14 => Some(0xf1),
      Code::F15 => Some(0xf2),
      Code::F16 => Some(0xf3),
      Code::F17 => Some(0xf4),
      Code::F18 => Some(0xf5),
      Code::F19 => Some(0xf6),
      Code::F20 => Some(0xf7),
      Code::F21 => Some(0xf8),
      Code::F22 => Some(0xf9),
      Code::F23 => Some(0xfa),
      Code::F24 => Some(0xfb),
      _ => None,
    }
  }
}
